export const environment = {
    production: true,
    dotnetApi: 'https://laylaerp.com/api/api/',
    apiBaseUrl: 'https://quickfixtest4.com/',
    siteBaseUrl: 'https://quickfixtest4.com/',
    GTM_ID: 'GTM-5B9DLF5F',
    YOTPO_API_KEY: 'W4P859PESTjtVk3gTPvm7sDuznsOgUohE9v6CtUf',
    YOTPO_BASE_URL: 'https://api.yotpo.com',
    AFFIRM_PUBLIC_KEY_SANDBOX: 'D7J2UM97ED9GWHG0',
    AFFIRM_PUBLIC_KEY_LIVE: 'ZFYHP0LPSTD45QXV',
    // cdnUrl: 'https://quickfixtest4.com/',
    cdnUrl: 'https://quickfixtest4.b-cdn.net/',
    // cdnUrl: '',
    zendeskApi: 'https://laylasleep.zendesk.com/api/v2/help_center',
    saleTitle: `SPRING SALE`,
};
